# GitHub Actions Workflow for danpearson.net Edge Functions
# Place this file in: .github/workflows/deploy-edge-functions.yml

name: Deploy Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'danpearson-edge-functions/**'
      - '.github/workflows/deploy-edge-functions.yml'
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: danpearson/edge-functions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./danpearson-edge-functions
          file: ./danpearson-edge-functions/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Trigger Coolify Deployment
        if: success()
        run: |
          curl -X POST "${{ secrets.COOLIFY_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "main",
              "message": "Deploy edge functions - ${{ github.sha }}"
            }'

      - name: Wait for deployment
        run: sleep 30

      - name: Verify deployment
        run: |
          echo "Checking health endpoint..."
          
          # Retry logic
          MAX_RETRIES=10
          RETRY_DELAY=10
          
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i of $MAX_RETRIES..."
            
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://functions.danpearson.net/_health)
            
            if [ "$RESPONSE" = "200" ]; then
              echo "✅ Deployment successful! Health check passed."
              
              # Get and display health data
              curl -s https://functions.danpearson.net/_health | jq '.'
              
              exit 0
            fi
            
            echo "Health check returned $RESPONSE, retrying in ${RETRY_DELAY}s..."
            sleep $RETRY_DELAY
          done
          
          echo "❌ Deployment verification failed after $MAX_RETRIES attempts"
          exit 1

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Edge Functions deployment failed!"
          echo "Check the logs for details."
          # Add notification logic here (Slack, Discord, email, etc.)

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Edge Functions deployed successfully!"
          echo "🔗 https://functions.danpearson.net"
          # Add notification logic here (Slack, Discord, email, etc.)

  test-functions:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Test health endpoint
        run: |
          curl -f https://functions.danpearson.net/_health

      - name: Test public function
        run: |
          curl -f -X POST https://functions.danpearson.net/health-check \
            -H "Content-Type: application/json" \
            -d '{}'

      - name: Get function list
        run: |
          echo "Available functions:"
          curl -s https://functions.danpearson.net/ | jq '.functions'

# Optional: Add job for running tests
#      - name: Run integration tests
#        run: |
#          npm install
#          npm run test:integration

# Optional: Add job for notification to Slack/Discord
#  notify:
#    needs: [build-and-deploy, test-functions]
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      - name: Send notification
#        uses: slackapi/slack-github-action@v1
#        with:
#          payload: |
#            {
#              "text": "Edge Functions Deployment ${{ job.status }}",
#              "blocks": [
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "*Deployment Status:* ${{ job.status }}\n*Commit:* ${{ github.sha }}\n*Branch:* ${{ github.ref_name }}"
#                  }
#                }
#              ]
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
