// Generated by scripts/generate-article-fallback.mjs. Do not edit.
//
// Article metadata without the bodies, for listing pages. Edit the markdown in
// content/crm and regenerate.

export interface StaticArticleSummary {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  tags: string[];
  author: string;
  read_time: string;
  featured: boolean;
  seo_title: string;
  seo_description: string;
  seo_keywords: string[];
  published_at: string;
  updated_at: string;
}

export const CRM_ARTICLE_INDEX: StaticArticleSummary[] = [
  {
    slug: 'agentic-crm-what-actually-works',
    title: 'Agentic CRM: What Actually Works Today',
    excerpt:
      'Agentic CRM works today for narrow, bounded, reviewable tasks and fails predictably at everything else. The failures are almost never model failures - they are prerequisite failures. Here is the capability map and how to tell which side of it a vendor demo sits on.',
    category: 'CRM',
    tags: [
      'CRM',
      'CRM Automation',
      'AI Agents',
      'RevOps',
      'Sales Automation',
      'HubSpot',
      'Salesforce',
    ],
    author: 'Dan Pearson',
    read_time: '14 min read',
    featured: true,
    seo_title: 'Agentic CRM in 2026: What Actually Works and What Does Not',
    seo_description:
      'An honest capability map for agentic CRM: the tasks AI agents genuinely handle in production today, the ones that fail predictably, why the failures are prerequisite failures rather than model failures, and the questions to ask a vendor.',
    seo_keywords: [
      'agentic CRM',
      'AI agents in CRM',
      'agentic AI sales',
      'autonomous CRM agents',
      'Agentforce vs Breeze',
      'AI agent supervision',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'ai-crm-automation-complete-guide',
    title: 'AI CRM Automation: The Complete 2026 Guide',
    excerpt:
      'AI CRM automation means using language models and agents to do the CRM work people currently do by hand. The catch is sequence: teams that automate reporting before capture end up with better-looking dashboards built on the same bad data. Here is what actually works, in the order it works.',
    category: 'CRM',
    tags: ['CRM', 'CRM Automation', 'Sales Automation', 'AI Agents', 'RevOps', 'Pipeline'],
    author: 'Dan Pearson',
    read_time: '14 min read',
    featured: true,
    seo_title: 'AI CRM Automation: The Complete 2026 Guide',
    seo_description:
      'What AI CRM automation actually is in 2026, what is genuinely automatable today, and the order to do it in. Includes the Pipeline Automation Ladder and a vendor-neutral platform assessment.',
    seo_keywords: [
      'AI CRM automation',
      'CRM automation guide',
      'agentic CRM',
      'CRM data quality',
      'sales pipeline automation',
      'HubSpot automation',
      'Salesforce automation',
    ],
    published_at: '2026-08-11',
    updated_at: '2026-08-11',
  },
  {
    slug: 'automating-call-logging-and-note-capture',
    title: 'Automating Call Logging and Note Capture: A Build Teardown',
    excerpt:
      'Call and meeting capture is the first path worth automating, and roughly a fifth of the work is the AI. Here is the whole build: the extraction schema, the confidence thresholds, where the write-back actually lands, and the seven failure modes that decide whether it is still running next year.',
    category: 'CRM',
    tags: [
      'CRM',
      'CRM Automation',
      'Sales Automation',
      'RevOps',
      'Pipeline',
      'AI Agents',
      'HubSpot',
    ],
    author: 'Dan Pearson',
    read_time: '14 min read',
    featured: true,
    seo_title: 'Automating Call Logging and Note Capture: Build Teardown',
    seo_description:
      'The complete build for the first capture path worth automating: the extraction schema, confidence thresholds, write-back targeting, the confirmation surface reps will actually use, and the failure handling that decides whether it survives a year.',
    seo_keywords: [
      'automate call logging',
      'automate CRM note taking',
      'call logging automation',
      'meeting notes to CRM',
      'automate CRM data entry',
      'HubSpot call logging automation',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'crm-automation-for-construction-companies',
    title: 'CRM Automation for Construction Companies',
    excerpt:
      'Construction breaks generic CRM automation for three specific reasons: the pipeline unit is a bid, not a deal; the real system of record is the estimating software; and the relationships that decide who gets invited to bid live in inboxes nobody logs. Here is what to automate instead.',
    category: 'CRM',
    tags: [
      'CRM',
      'CRM Automation',
      'Construction',
      'Sales Automation',
      'RevOps',
      'Pipeline',
      'Preconstruction',
    ],
    author: 'Dan Pearson',
    read_time: '13 min read',
    featured: false,
    seo_title: 'CRM Automation for Construction Companies (2026 Guide)',
    seo_description:
      'Why generic CRM automation fails in construction, what to automate instead when the pipeline unit is a bid rather than a deal, and how to handle the fact that your real system of record is the estimating software.',
    seo_keywords: [
      'CRM automation for construction',
      'construction CRM',
      'preconstruction pipeline',
      'contractor CRM automation',
      'bid management automation',
      'construction sales automation',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'crm-automation-for-real-estate-teams',
    title: 'CRM Automation for Real Estate Teams',
    excerpt:
      'Real estate teams automate the first five minutes and neglect the next eighteen months, which is where the money actually is. Speed to lead is a solved problem. A database of 4,000 contacts nobody knows anything about is not.',
    category: 'CRM',
    tags: [
      'CRM',
      'CRM Automation',
      'Real Estate',
      'Sales Automation',
      'RevOps',
      'Pipeline',
      'Lead Management',
    ],
    author: 'Dan Pearson',
    read_time: '13 min read',
    featured: false,
    seo_title: 'CRM Automation for Real Estate Teams (2026 Guide)',
    seo_description:
      'Speed to lead is solved and most real estate teams still lose the database. What to automate when conversion happens 6 to 18 months out, why generic nurture fails, and how consent rules constrain the build.',
    seo_keywords: [
      'CRM automation for real estate',
      'real estate CRM automation',
      'speed to lead automation',
      'real estate lead nurture',
      'AI ISA real estate',
      'realtor CRM automation',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'get-sales-reps-to-use-the-crm',
    title: 'How to Get Sales Reps to Actually Use the CRM',
    excerpt:
      'You do not get reps to use the CRM by asking harder. Every lever most teams reach for — mandatory fields, adoption dashboards, tying it to comp — reliably makes the data worse, because none of them address the actual reason. Here is what does.',
    category: 'CRM',
    tags: ['CRM', 'CRM Automation', 'Sales Automation', 'Pipeline', 'RevOps'],
    author: 'Dan Pearson',
    read_time: '9 min read',
    featured: false,
    seo_title: 'How to Get Sales Reps to Actually Use the CRM (Without Nagging)',
    seo_description:
      'You do not get reps to use the CRM by asking harder. Every lever most teams reach for — mandatory fields, adoption dashboards, tying it to comp — makes the data worse. Here is what actually works.',
    seo_keywords: [
      'how to get sales reps to use the CRM',
      'CRM adoption',
      'sales reps not updating CRM',
      'CRM data quality',
      'CRM compliance',
    ],
    published_at: '2026-08-11',
    updated_at: '2026-08-11',
  },
  {
    slug: 'how-to-choose-a-crm-automation-consultant',
    title: 'How to Choose a CRM Automation Consultant (2026 Buyer Guide)',
    excerpt:
      'Most teams hire the wrong type of provider for the problem they actually have. Here are the three kinds of CRM automation consultant, the nine questions that tell you which one is in front of you, and the answers worth walking away from.',
    category: 'CRM',
    tags: [
      'CRM',
      'CRM Automation',
      'RevOps',
      'Sales Automation',
      'Consulting',
      'HubSpot',
      'Salesforce',
    ],
    author: 'Dan Pearson',
    read_time: '11 min read',
    featured: true,
    seo_title: 'How to Choose a CRM Automation Consultant: 9 Questions to Ask',
    seo_description:
      'A vendor-neutral guide to hiring a CRM automation consultant: the three types of provider, the nine questions that separate operators from resellers, what engagements cost, and the red flags worth walking away from.',
    seo_keywords: [
      'CRM automation consultant',
      'hire CRM automation expert',
      'CRM automation services',
      'RevOps consultant',
      'HubSpot automation consultant',
      'CRM automation agency',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'hubspot-breeze-vs-salesforce-agentforce',
    title: 'HubSpot Breeze vs Salesforce Agentforce for Teams Under 50 Seats',
    excerpt:
      'For most teams under 50 seats, HubSpot Breeze is the better buy — but the more useful answer is that a third of the teams asking this question should not buy either one yet. Here is the real pricing arithmetic and the honest verdict on each.',
    category: 'CRM',
    tags: ['CRM', 'CRM Automation', 'HubSpot', 'Salesforce', 'AI Agents', 'RevOps'],
    author: 'Dan Pearson',
    read_time: '12 min read',
    featured: true,
    seo_title: 'HubSpot Breeze vs Salesforce Agentforce: Honest 2026 Comparison',
    seo_description:
      'A vendor-neutral comparison of HubSpot Breeze and Salesforce Agentforce for revenue teams under 50 seats, with real 2026 pricing arithmetic — and the third option neither vendor will mention.',
    seo_keywords: [
      'HubSpot AI vs Salesforce Einstein',
      'HubSpot Breeze vs Agentforce',
      'Agentforce pricing',
      'Breeze AI pricing',
      'best AI CRM for small business',
      'agentic CRM comparison',
    ],
    published_at: '2026-08-11',
    updated_at: '2026-08-11',
  },
  {
    slug: 'pipeline-automation-ladder',
    title: 'The Pipeline Automation Ladder: A Maturity Model for CRM Automation',
    excerpt:
      'Five rungs, from a CRM nobody updates to a revenue system that maintains itself. The load-bearing rule is that rung 2 cannot be skipped, and this is what each rung looks like from inside a real team.',
    category: 'CRM',
    tags: [
      'CRM',
      'CRM Automation',
      'RevOps',
      'Sales Automation',
      'AI Agents',
      'Pipeline',
      'Framework',
    ],
    author: 'Dan Pearson',
    read_time: '13 min read',
    featured: true,
    seo_title: 'The Pipeline Automation Ladder: CRM Automation Maturity Model',
    seo_description:
      'A five-rung maturity model for CRM automation, with the diagnostic questions that place a team on a rung, worked examples at each level, and the reason rung 2 cannot be skipped.',
    seo_keywords: [
      'CRM automation maturity model',
      'pipeline automation ladder',
      'capture layer vs reporting layer',
      'CRM automation framework',
      'sales automation maturity',
      'agentic CRM readiness',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'what-crm-automation-costs',
    title: 'What CRM Automation Actually Costs in 2026',
    excerpt:
      'A first capture-layer build for a 20-seat team lands somewhere between $15,000 and $60,000 all-in for year one. Here is the arithmetic behind that range, the four buckets it splits into, and the much larger number most teams are already paying without seeing it on an invoice.',
    category: 'CRM',
    tags: ['CRM', 'CRM Automation', 'Pricing', 'RevOps', 'Sales Automation', 'Pipeline'],
    author: 'Dan Pearson',
    read_time: '12 min read',
    featured: false,
    seo_title: 'What CRM Automation Costs in 2026 (Worked Arithmetic)',
    seo_description:
      'The four cost buckets in a CRM automation project, worked end to end for a 20-seat sales team: diagnostic, build, platform licences and run costs, plus the cost of the manual capture you are already paying for.',
    seo_keywords: [
      'CRM automation cost',
      'how much does CRM automation cost',
      'CRM automation pricing',
      'AI CRM cost',
      'CRM automation ROI',
      'sales automation cost',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
  {
    slug: 'why-ai-crm-projects-fail',
    title: 'Why AI CRM Projects Fail: Five Failure Modes',
    excerpt:
      'Most AI CRM projects fail for a single reason: they automate the reporting layer instead of the capture layer. That root cause shows up as five recognisable failure modes. Here is how to tell which one you are in.',
    category: 'CRM',
    tags: ['CRM', 'CRM Automation', 'Sales Automation', 'AI Agents', 'RevOps', 'Pipeline'],
    author: 'Dan Pearson',
    read_time: '11 min read',
    featured: true,
    seo_title: 'Why AI CRM Projects Fail: Five Failure Modes (2026)',
    seo_description:
      'Most AI CRM projects fail for one root reason, which then shows up as five recognisable failure modes. How to tell which one you are in, and what to do about it.',
    seo_keywords: [
      'why do AI CRM projects fail',
      'AI CRM failure',
      'CRM data quality problems',
      'sales reps not updating CRM',
      'is CRM AI worth it',
      'agentic CRM risk',
    ],
    published_at: '2026-08-11',
    updated_at: '2026-08-11',
  },
  {
    slug: 'zapier-vs-make-vs-n8n-for-crm-automation',
    title: 'Zapier vs Make vs n8n for CRM Automation',
    excerpt:
      'Start on Zapier, move to Make when the logic branches, run n8n when you need control over data and cost. The tool matters far less than most comparisons suggest, and here is the part that actually decides whether your automation survives a year.',
    category: 'CRM',
    tags: ['CRM', 'CRM Automation', 'Zapier', 'Make', 'n8n', 'Sales Automation', 'RevOps'],
    author: 'Dan Pearson',
    read_time: '12 min read',
    featured: false,
    seo_title: 'Zapier vs Make vs n8n for CRM Automation: Honest 2026 Comparison',
    seo_description:
      'Which automation platform to use for CRM work, judged on the things that actually matter at the capture layer: error handling, cost at volume, AI steps and what happens when a run fails at 2am.',
    seo_keywords: [
      'Zapier vs Make vs n8n',
      'best automation tool for CRM',
      'n8n CRM automation',
      'Make vs Zapier CRM',
      'CRM integration platform',
      'automate CRM data entry',
    ],
    published_at: '2026-08-14',
    updated_at: '2026-08-14',
  },
];
