-- Command Center Schema: System monitoring, alerts, and admin activity tracking

-- System metrics tracking table
CREATE TABLE IF NOT EXISTS public.system_metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_type text NOT NULL, -- 'error_rate', 'api_latency', 'db_connections', 'page_views', 'cache_hit_rate'
  metric_name text NOT NULL,
  value numeric NOT NULL,
  unit text, -- 'ms', 'count', 'percentage', 'bytes'
  page_url text,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Alert rules configuration
CREATE TABLE IF NOT EXISTS public.alert_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_type text NOT NULL, -- 'error_spike', 'traffic_drop', 'slow_query', 'webhook_failure'
  alert_name text NOT NULL,
  description text,
  metric_type text NOT NULL,
  threshold_value numeric NOT NULL,
  threshold_operator text NOT NULL DEFAULT '>',  -- '>', '<', '>=', '<=', '='
  time_window_minutes integer DEFAULT 60, -- Look back period
  enabled boolean DEFAULT true,
  severity text NOT NULL DEFAULT 'warning', -- 'info', 'warning', 'critical'
  notification_channels text[] DEFAULT ARRAY['dashboard']::text[], -- 'dashboard', 'email', 'slack'
  last_triggered_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Admin activity log for audit trail
CREATE TABLE IF NOT EXISTS public.admin_activity_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  admin_email text NOT NULL,
  action text NOT NULL, -- 'published_article', 'deleted_submission', 'ran_pipeline', 'cleared_cache'
  action_category text, -- 'content', 'settings', 'maintenance', 'support'
  resource_type text, -- 'article', 'project', 'ai_tool', 'webhook'
  resource_id uuid,
  resource_title text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text,
  timestamp timestamp with time zone NOT NULL DEFAULT now()
);

-- Automated alerts generated by the system
CREATE TABLE IF NOT EXISTS public.automated_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_rule_id uuid REFERENCES public.alert_rules(id) ON DELETE SET NULL,
  alert_type text NOT NULL,
  severity text NOT NULL, -- 'info', 'warning', 'critical'
  title text NOT NULL,
  message text NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  acknowledged boolean DEFAULT false,
  acknowledged_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  acknowledged_at timestamp with time zone,
  resolved boolean DEFAULT false,
  resolved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Quick stats cache for dashboard performance
CREATE TABLE IF NOT EXISTS public.dashboard_stats_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stat_key text NOT NULL UNIQUE, -- 'total_articles', 'total_views', 'revenue_today', 'active_users'
  stat_value jsonb NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.system_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automated_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_stats_cache ENABLE ROW LEVEL SECURITY;

-- RLS Policies: System metrics (service can insert, admins can read)
CREATE POLICY "Service can create system metrics"
ON public.system_metrics
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Admins can read system metrics"
ON public.system_metrics
FOR SELECT
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete old metrics"
ON public.system_metrics
FOR DELETE
USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies: Alert rules (admins only)
CREATE POLICY "Admins can manage alert rules"
ON public.alert_rules
FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies: Admin activity log (admins can read, service can insert)
CREATE POLICY "Service can create activity logs"
ON public.admin_activity_log
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Admins can read activity logs"
ON public.admin_activity_log
FOR SELECT
USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies: Automated alerts (service can insert, admins can manage)
CREATE POLICY "Service can create automated alerts"
ON public.automated_alerts
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Admins can read automated alerts"
ON public.automated_alerts
FOR SELECT
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update automated alerts"
ON public.automated_alerts
FOR UPDATE
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete automated alerts"
ON public.automated_alerts
FOR DELETE
USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies: Dashboard stats cache (service can manage, admins can read)
CREATE POLICY "Service can manage dashboard stats"
ON public.dashboard_stats_cache
FOR ALL
WITH CHECK (true);

CREATE POLICY "Admins can read dashboard stats"
ON public.dashboard_stats_cache
FOR SELECT
USING (has_role(auth.uid(), 'admin'::app_role));

-- Indexes for performance
CREATE INDEX idx_system_metrics_type ON public.system_metrics(metric_type);
CREATE INDEX idx_system_metrics_recorded_at ON public.system_metrics(recorded_at DESC);
CREATE INDEX idx_system_metrics_type_recorded ON public.system_metrics(metric_type, recorded_at DESC);

CREATE INDEX idx_alert_rules_enabled ON public.alert_rules(enabled) WHERE enabled = true;
CREATE INDEX idx_alert_rules_type ON public.alert_rules(alert_type);

CREATE INDEX idx_admin_activity_admin_email ON public.admin_activity_log(admin_email);
CREATE INDEX idx_admin_activity_action ON public.admin_activity_log(action);
CREATE INDEX idx_admin_activity_timestamp ON public.admin_activity_log(timestamp DESC);
CREATE INDEX idx_admin_activity_resource ON public.admin_activity_log(resource_type, resource_id);

CREATE INDEX idx_automated_alerts_severity ON public.automated_alerts(severity);
CREATE INDEX idx_automated_alerts_acknowledged ON public.automated_alerts(acknowledged) WHERE acknowledged = false;
CREATE INDEX idx_automated_alerts_created_at ON public.automated_alerts(created_at DESC);

CREATE INDEX idx_dashboard_stats_expires ON public.dashboard_stats_cache(expires_at);

-- Triggers for updated_at
CREATE TRIGGER update_alert_rules_updated_at
BEFORE UPDATE ON public.alert_rules
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_dashboard_stats_updated_at
BEFORE UPDATE ON public.dashboard_stats_cache
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Function to log admin activity automatically
CREATE OR REPLACE FUNCTION log_admin_activity(
  p_admin_email text,
  p_action text,
  p_action_category text DEFAULT NULL,
  p_resource_type text DEFAULT NULL,
  p_resource_id uuid DEFAULT NULL,
  p_resource_title text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_log_id uuid;
BEGIN
  INSERT INTO public.admin_activity_log (
    admin_id,
    admin_email,
    action,
    action_category,
    resource_type,
    resource_id,
    resource_title,
    metadata
  ) VALUES (
    auth.uid(),
    p_admin_email,
    p_action,
    p_action_category,
    p_resource_type,
    p_resource_id,
    p_resource_title,
    p_metadata
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

-- Function to record system metric
CREATE OR REPLACE FUNCTION record_metric(
  p_metric_type text,
  p_metric_name text,
  p_value numeric,
  p_unit text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_metric_id uuid;
BEGIN
  INSERT INTO public.system_metrics (
    metric_type,
    metric_name,
    value,
    unit,
    metadata
  ) VALUES (
    p_metric_type,
    p_metric_name,
    p_value,
    p_unit,
    p_metadata
  )
  RETURNING id INTO v_metric_id;

  RETURN v_metric_id;
END;
$$;

-- Function to check alert rules and create alerts
CREATE OR REPLACE FUNCTION check_alert_rules()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_rule RECORD;
  v_metric_value numeric;
  v_triggered boolean;
BEGIN
  -- Loop through all enabled alert rules
  FOR v_rule IN
    SELECT * FROM public.alert_rules
    WHERE enabled = true
  LOOP
    -- Calculate metric value based on time window
    SELECT
      CASE
        WHEN v_rule.metric_type = 'error_rate' THEN COUNT(*)
        WHEN v_rule.metric_type = 'api_latency' THEN AVG(value)
        ELSE AVG(value)
      END
    INTO v_metric_value
    FROM public.system_metrics
    WHERE
      metric_type = v_rule.metric_type
      AND recorded_at > now() - (v_rule.time_window_minutes || ' minutes')::interval;

    -- Check if threshold is crossed
    v_triggered := CASE v_rule.threshold_operator
      WHEN '>' THEN v_metric_value > v_rule.threshold_value
      WHEN '<' THEN v_metric_value < v_rule.threshold_value
      WHEN '>=' THEN v_metric_value >= v_rule.threshold_value
      WHEN '<=' THEN v_metric_value <= v_rule.threshold_value
      WHEN '=' THEN v_metric_value = v_rule.threshold_value
      ELSE false
    END;

    -- Create alert if triggered and not recently triggered (prevent spam)
    IF v_triggered AND (
      v_rule.last_triggered_at IS NULL OR
      v_rule.last_triggered_at < now() - interval '1 hour'
    ) THEN
      INSERT INTO public.automated_alerts (
        alert_rule_id,
        alert_type,
        severity,
        title,
        message,
        details
      ) VALUES (
        v_rule.id,
        v_rule.alert_type,
        v_rule.severity,
        v_rule.alert_name,
        format('Alert triggered: %s. Current value: %s, Threshold: %s %s',
          v_rule.description,
          v_metric_value,
          v_rule.threshold_operator,
          v_rule.threshold_value
        ),
        jsonb_build_object(
          'metric_value', v_metric_value,
          'threshold', v_rule.threshold_value,
          'time_window_minutes', v_rule.time_window_minutes
        )
      );

      -- Update last triggered time
      UPDATE public.alert_rules
      SET last_triggered_at = now()
      WHERE id = v_rule.id;
    END IF;
  END LOOP;
END;
$$;

-- Insert default alert rules
INSERT INTO public.alert_rules (alert_type, alert_name, description, metric_type, threshold_value, threshold_operator, time_window_minutes, severity) VALUES
('error_spike', 'Error Spike Alert', 'Alert when error rate exceeds 10 in the last hour', 'error_rate', 10, '>', 60, 'critical'),
('slow_api', 'Slow API Response', 'Alert when average API latency exceeds 2000ms', 'api_latency', 2000, '>', 30, 'warning'),
('traffic_drop', 'Traffic Drop Alert', 'Alert when page views drop below 50% of average', 'page_views', 50, '<', 60, 'warning');

-- Comment on tables
COMMENT ON TABLE public.system_metrics IS 'Stores real-time system metrics for monitoring dashboard';
COMMENT ON TABLE public.alert_rules IS 'Configuration for automated alerting system';
COMMENT ON TABLE public.admin_activity_log IS 'Audit trail of all admin actions';
COMMENT ON TABLE public.automated_alerts IS 'System-generated alerts from monitoring';
COMMENT ON TABLE public.dashboard_stats_cache IS 'Cached statistics for dashboard performance';
