-- Create the update_updated_at_column function
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create projects table
CREATE TABLE public.projects (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  tags TEXT[] DEFAULT '{}',
  status TEXT DEFAULT 'Active',
  featured BOOLEAN DEFAULT false,
  github_link TEXT,
  live_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Projects can be read by everyone"
ON public.projects
FOR SELECT
USING (true);

CREATE POLICY "Projects can be created"
ON public.projects
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Projects can be updated"
ON public.projects
FOR UPDATE
USING (true);

CREATE POLICY "Projects can be deleted"
ON public.projects
FOR DELETE
USING (true);

-- Create updated_at trigger
CREATE TRIGGER update_projects_updated_at
  BEFORE UPDATE ON public.projects
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert sample projects from the documentation
INSERT INTO public.projects (title, description, image_url, tags, featured) VALUES
('Project Nexus AI', 'Nexus AI, where art meets technology in a whole new way. We are a one-of-a-kind NFT project that takes creativity and randomness to the next level. With over 1.56 x 10^93 total combinations, each NFT generated by Nexus AI is truly unique.', NULL, '{"NFT", "AI", "Blockchain", "Art"}', true),
('Ninjoon', 'A collection of 1,500 unique generative NFTs from your own backyard. Think of them as your own personal sidekick – Defeat evil, Display on your mantle or just have a cute Ninjoon in your wallet.', NULL, '{"NFT", "Generative", "Collection"}', true),
('VidChain', 'VidChain.io is a blockchain-based platform that transforms video content into verifiable NFTs, empowering creators with ownership, transparency, and automated royalties.', NULL, '{"Blockchain", "Video", "NFT", "Platform"}', true),
('Concept Design', 'Creative concept design services combining artistic vision with technical implementation for digital products and experiences.', NULL, '{"Design", "Concept", "Creative"}', false),
('Website Development', 'Full-stack web development services creating modern, responsive, and user-friendly websites tailored to client needs.', NULL, '{"Web Dev", "Frontend", "Backend"}', false),
('AI Integration', 'Implementing cutting-edge AI solutions using OpenAI, Auto-GPT, and other advanced technologies to enhance business operations.', NULL, '{"AI", "OpenAI", "Automation"}', false);