-- Seed the AI CRM automation FAQ set.
--
-- These ten answers are the same set rendered on /ai-crm-automation (see
-- src/lib/crm-automation.ts). Loading them here makes them appear on /faq as
-- well, where the page already emits FAQPage schema from the database — so the
-- category's questions become rich-result and citation eligible with no further
-- code. Editing them afterwards in the admin is expected; this migration only
-- seeds rows that are not already present.

INSERT INTO faqs (question, answer, category, display_order, featured, status)
SELECT * FROM (VALUES
  ('What is AI CRM automation?', 'AI CRM automation is the use of language models and AI agents to do the work that a CRM normally asks people to do by hand: logging calls and meetings, writing notes, enriching records, routing leads, spotting stalled deals and keeping deal stages honest. It differs from traditional CRM automation, which is rule-based and deterministic — a rule fires when a condition is met. AI automation can work from unstructured input like a call transcript or an email thread, which is what makes it able to handle the capture problem that rules never could.', 'CRM Automation', 10, true, 'published'),
  ('Why do most AI CRM projects fail?', 'Because they automate the reporting layer instead of the capture layer. The visible, fundable, demo-friendly work is summarisation, scoring and forecasting — all of which sit downstream of data that reps enter by hand, late, from memory. When the input is sparse, AI output is confidently wrong, trust collapses and the feature gets switched off. Teams that automate capture first find the downstream AI starts working almost on its own, because it finally has dense, recent, structured history to reason over.', 'CRM Automation', 20, true, 'published'),
  ('What is the difference between the capture layer and the reporting layer?', 'The capture layer is everything that puts information into the CRM: call logging, note-taking, email sync, contact enrichment, stage changes. The reporting layer is everything that reads it back out: dashboards, forecasts, lead scores, summaries, alerts. Most CRM spending goes to the reporting layer because that is what executives see. But the reporting layer can only ever be as good as the capture layer feeding it, and the capture layer is where nearly all the manual effort and nearly all the data loss actually happen.', 'CRM Automation', 30, true, 'published'),
  ('How much does CRM automation cost?', 'The audit is $2,500, flat, and takes two weeks. You get a findings document and a prioritised roadmap that is yours to keep regardless of who implements it. Build and retainer work is scoped out of that audit rather than quoted up front, because the cost depends almost entirely on how many capture paths need automating and what integration work sits underneath — and neither of us knows that before the audit. Anyone who quotes an implementation number before looking at your data is guessing. Platform and API costs sit on top and are usually modest by comparison; the expensive part of CRM automation has always been the thinking, not the tokens.', 'CRM Automation', 40, false, 'published'),
  ('How long does a CRM automation project take?', 'The audit is two weeks. A first capture-layer build is usually four to twelve weeks depending on scope, and it is deliberately sequenced so something useful ships in the first fortnight rather than everything landing at the end. Teams generally feel the difference in seller hours within the first month, while forecast accuracy takes a full quarter to show, because you need a complete cycle of clean data before the comparison means anything.', 'CRM Automation', 50, false, 'published'),
  ('Do I need to switch CRMs to automate with AI?', 'Almost never, and being told to switch early is a warning sign. HubSpot, Salesforce, Pipedrive, GoHighLevel and Zoho are all automatable to a useful depth, and the migration cost of switching usually exceeds the cost of fixing what you have. A platform change is worth considering only when the current system genuinely cannot represent how you sell — and that is a much rarer diagnosis than the people selling migrations suggest.', 'CRM Automation', 60, false, 'published'),
  ('Will AI automation make my sales forecast accurate?', 'Indirectly, and only in that order. Forecasting models fail on sparse and stale data far more often than they fail on modelling. When capture is automated, the forecast improves substantially before anyone touches the forecasting logic, because the model is finally reading a record of what happened rather than a rep''s Friday-afternoon reconstruction of it. Automating the forecast first, on manual capture, is the single most common way to spend real money and change nothing.', 'CRM Automation', 70, false, 'published'),
  ('How is this different from RevOps consulting?', 'RevOps consulting typically covers process design, territory and comp planning, tooling strategy and reporting structure across the whole revenue organisation. This is narrower and more technical: the automation layer inside the CRM, built and shipped rather than specified. Plenty of teams need both. If you do not have a defined sales process yet, RevOps comes first — automation makes an existing process cheaper to run, it does not invent one for you.', 'CRM Automation', 80, false, 'published'),
  ('Can a team under 20 seats justify CRM automation?', 'Often more easily than a large one, because small teams have no operations staff absorbing the manual work — it comes straight out of selling time. The arithmetic is simple: multiply seats by hours per week spent on CRM admin by loaded hourly cost. Teams in the five-to-twenty range routinely find several hours per rep per week, which pays for a capture-layer build inside a year while also making the pipeline legible for the first time.', 'CRM Automation', 90, false, 'published'),
  ('What is agentic CRM and is it ready?', 'Agentic CRM means AI that executes inside the system rather than just recommending — qualifying inbound, chasing stalled deals, booking meetings, updating records under supervision. As of 2026 it is genuinely ready for narrow, well-bounded, reviewable tasks, and genuinely not ready to be handed a messy pipeline and left alone. That is rung 3 on the Pipeline Automation Ladder, and it works when rung 2 is solid underneath it. On manual capture, an agent simply makes mistakes faster than a human would.', 'CRM Automation', 100, false, 'published')
) AS seed(question, answer, category, display_order, featured, status)
WHERE NOT EXISTS (
  SELECT 1 FROM faqs f WHERE f.question = seed.question
);
