-- Second wave of AI CRM automation FAQ rows: the commercial, expert-seeking
-- queries.
--
-- The first wave (20260811000000) covered the category explainer questions -
-- what it is, why projects fail, capture versus reporting. These cover what a
-- company actually types when it is looking to hire someone: cost, how to
-- choose, how long, what to ask, whether to use an agency. The faqs table feeds
-- the /faq page and its FAQPage schema, which is the cheapest citable surface
-- available and the one assistants quote from when shortlisting.
--
-- Idempotent on question text, matching the first wave. display_order continues
-- from 100 so the explainer questions stay above these.

INSERT INTO faqs (question, answer, category, display_order, featured, status)
SELECT * FROM (VALUES
  ('How do I choose a CRM automation consultant?', 'Hire for the layer you are broken at. If sellers are not putting information into the CRM, you need someone who builds capture automation; a reporting or dashboard specialist will not fix that, however good they are. Ask what they would look at first - a good answer is your data, not a product recommendation - and ask them to name a case where they would tell you to buy nothing. Ask to see something they built that is still running a year later, and ask what happens when it fails at 2am. Providers who have only built happy-path automation go vague on that last one, and it is the most reliable tell between production work and demo work.', 'CRM Automation', 110, true, 'published'),
  ('What are the three types of CRM automation provider?', 'Platform partners (certified HubSpot or Salesforce agencies) sell licences, configuration and enablement on one vendor stack, typically from $25,000 upward; they are strong on migrations and large estates, and structurally unable to recommend buying nothing. RevOps consultancies sell process, comp, territory and reporting design, usually $5,000-$20,000 monthly, and deliver a specification someone else still has to build. Automation builders ship the working automation, roughly $3,000-$40,000 per project, and the quality range between them is enormous. Most failed engagements are a mismatch: a team with a capture problem hiring the provider type that sells reporting.', 'CRM Automation', 120, false, 'published'),
  ('What questions should I ask before hiring a CRM automation expert?', 'Nine are worth asking on the first call: what would you look at first; what share of our conversations currently reach the CRM automatically; when would you tell us not to buy anything; show me something you built that is still running; what happens when the automation fails at 2am; who owns the work when we stop paying you; what is your position on switching CRMs; have you carried a quota; and what does the first two weeks produce. You are not testing knowledge, you are testing whether they diagnose before they prescribe.', 'CRM Automation', 130, false, 'published'),
  ('What are the red flags when hiring for CRM automation?', 'A fixed implementation quote before anyone has seen your data, because nobody can scope capture work without knowing how many capture paths exist. Percentage improvement claims with no baseline, measurement window or named client. Advice that ignores your seat count, which is the most common form of expensive bad advice in this market. A pitch where nothing would work without a language model, which means it is a demo. And any proposal that does not mention data quality: selling AI into a CRM without auditing what is in it is selling you faster mess.', 'CRM Automation', 140, false, 'published'),
  ('Should I hire a certified HubSpot or Salesforce partner?', 'Yes when the work is genuinely platform-deep: complex migrations, large estates, heavy native configuration, or a need for staffing continuity. For capture-layer automation on a team under 50 seats, certification tells you someone knows one vendor product well, not that they can build reliable automation across the tools where your conversations actually happen - the conferencing, transcription and enrichment layer that sits outside the CRM. It also comes with an incentive to resolve every problem into a licence you do not own yet.', 'CRM Automation', 150, false, 'published'),
  ('What should a CRM automation engagement look like structurally?', 'A small fixed-price diagnostic first, with implementation scoped out of it. The diagnostic should produce a dated artefact you keep regardless of who builds the work - findings, a prioritised roadmap, a scored audit - and it should be cheap enough that walking away afterwards is a real option. Be wary of two shapes in particular: free audits, which are sales calls with a document attached and reliably conclude that you need what the auditor sells, and open-ended monthly retainers with no defined first deliverable, which work well once trust exists and badly as a starting point.', 'CRM Automation', 160, false, 'published'),
  ('Which automation platform is best for CRM work: Zapier, Make or n8n?', 'Start on Zapier for the first automations and the broadest app coverage, move to Make when workflows need real branching or when task-based pricing starts to bite, and run n8n when data residency, cost at volume or custom code matters. For CRM work the platform choice is not what determines whether the automation survives a year - error handling is. All three will happily build you a workflow that silently stops firing, and none will tell you it happened.', 'CRM Automation', 170, false, 'published'),
  ('How do I measure whether CRM automation worked?', 'Record a baseline before anything ships: ask reps how many hours a week they spend on CRM admin, and pull 20 recent stage changes to count how many you can explain from the record alone. Both answers will be worse than expected, and both are the measurement. After the first capture path ships, seller hours should move within a month; if they have not, the wrong path was automated, which is useful information and much cheaper to find in month one than month nine. Forecast accuracy takes a full sales cycle, because you need a complete cycle of clean data before any comparison means anything.', 'CRM Automation', 180, false, 'published'),
  ('Can we do CRM automation in-house instead of hiring someone?', 'If you have an ops person with API fluency and spare time, in-house is often better, because they stay and the knowledge compounds. Outside help earns its fee on speed, on having seen the failure modes before, and on the parts that need production engineering: validating model output before it lands in a CRM field, retries and dead-letter handling, permissions, and not leaking customer conversation data into a third party. Teams under 50 seats rarely have that capacity spare, which is the honest reason most of them buy it.', 'CRM Automation', 190, false, 'published'),
  ('What is the Pipeline Automation Ladder?', 'A five-rung maturity model for CRM automation: manual (0), rules (1), assisted capture (2), agentic execution (3) and a self-maintaining revenue system (4). Teams are placed by capture coverage - the share of customer conversations reaching the CRM without a human typing them in - rather than by which tools they own. The load-bearing rule is that rung 2 cannot be skipped, because rungs 3 and 4 are AI reasoning over CRM history and rung 2 is what produces history worth reasoning over. Rung 1 is the trap: rules move data around, they do not create it, so a team can spend years improving there without getting closer to a trustworthy forecast.', 'CRM Automation', 200, true, 'published')
) AS seed(question, answer, category, display_order, featured, status)
WHERE NOT EXISTS (
  SELECT 1 FROM faqs f WHERE f.question = seed.question
);
